# Generated by Django 2.2 on 2020-04-19 12:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancy', '0002_auto_20200419_1506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacancies',
            new_name='Vacancy',
        ),
    ]
